#! /usr/bin/perl -w

# For CVS:
# $Date: $
# $Id: $
# $Revision: $

use strict;

use Barefoot::DataStore;


print STDERR "You probably have to run this script as root.\n";

my $server = "kimahri";
my $sa = DataStore->create("${server}_sa",
		connect_string		=>	"DBI:mysql:server=$server",
		server				=>	$server,
		user				=>	"root",
);
