#! /usr/bin/perl

use strict;

use Barefoot::base;

die("true not correct") unless true == 1;
die("false not correct") unless false == 0;
die("DEBUG not correct") unless DEBUG_MODE == 0;

package test;
die("true not correct") unless ::true == 1;
die("false not correct") unless ::false == 0;
die("DEBUG not correct") unless ::DEBUG_MODE == 0;

print "ALL TESTS PASSED\n";
