#! /usr/bin/perl -w

use strict;

use Barefoot::base;

die("true not correct") unless true == 1;
die("false not correct") unless false == 0;
die("DEBUG not correct") unless DEBUG == 0;

package test;
use Barefoot::base;
die("true not correct") unless true == 1;
die("false not correct") unless false == 0;
die("DEBUG not correct") unless DEBUG == 0;

package test2;
sub DEBUG () { return "test2"; }
use Barefoot::base;
die("true not correct") unless true == 1;
die("false not correct") unless false == 0;
die("DEBUG not correct") unless DEBUG eq "test2";

package test3;
use Barefoot::base;
die("true not correct") unless true == 1;
die("false not correct") unless false == 0;
die("DEBUG not correct") unless DEBUG == 0;

system("test_base2");

print "ALL TESTS PASSED\n";
