#! /usr/bin/perl -w

use strict;

use Barefoot::debug;
use Barefoot::test_debug;

die("DEBUG not correct") unless DEBUG == 1;

package test;
BEGIN
{
	eval "use Barefoot::base; use Barefoot::debug;";

	die("debug didn't catch that base loaded first")
			unless $@ =~ /^DEBUG already defined/;
}

package test2;
BEGIN
{
	die("debug didn't set higher level for value: $@")
			unless eval "use Barefoot::debug(2); DEBUG;" == 2;
}

print "ALL TESTS PASSED\n";
