#! /usr/bin/perl

use strict;

use Barefoot::date;
use Barefoot::input qw(get_yn input);
use Barefoot::timerdata;


################
#    main()    #
################

my $log_id = $ARGV[0];
$log_id = input("Time log ID:") unless defined($log_id);

my $rows = timerdata::query_results("
		select e.fname, tl.client, c.name, tl.proj, tl.phase, tl.cliproj,
				convert(char(10), tl.date, 101), tl.hours
		from time_log tl, employee e, client c
		where tl.log_id = $log_id
		and tl.emp = e.emp
		and tl.client = c.client
	");
die("couldn't access timer database") unless defined($rows);
die("bad time log id:".scalar(@$rows)) unless @$rows == 1;

my $employee = $rows->[0]->[0];
my $client = $rows->[0]->[1];
my $client_name = $rows->[0]->[2];
my $proj = $rows->[0]->[3];
my $phase = $rows->[0]->[4];
my $cliproj = $rows->[0]->[5];
my $date = $rows->[0]->[6];
my $hours = $rows->[0]->[7];

print "\nTime log for employee $employee, client $client_name, "
		. "proj $proj,\n    phase $phase, cliproj $cliproj, date $date, "
		. "hours $hours\n";
exit 1 unless get_yn("Is this right?");

$client = input("New client?", $client);
$proj = input("New proj?", $proj);
$phase = input("New phase?", $phase);
$cliproj = input("New cliproj?", $cliproj);
$date = input("New date?", $date);
$hours = input("New number of hours?", $hours);
die("illegal date") unless date::isValid($date);

$proj = string::upper($proj);
$phase = string::upper($phase);
$cliproj = string::upper($cliproj);

$cliproj = "'$cliproj'" unless $cliproj eq "NULL";
my $update_query = "
	update time_log
	set client = '$client', proj = '$proj', phase = '$phase',
			cliproj = $cliproj, date = '$date', hours = $hours,
			chguser = '$::ENV{USER}', chgdate = getdate()
	where log_id = $log_id
	go
";

timerdata::set_user($::ENV{USER});
my $results = timerdata::run_query("
	begin tran
	go

	$update_query

	rollback tran
	go
");
die("mark failed <<$results>>") unless
		$results =~ /^\(1 row affected\)\s*$/;

print "\nInitial attempt successful for employee $employee, client $client,\n";
print "    new proj $proj, new phase $phase, new cliproj $cliproj\n";
exit 1 unless get_yn("Proceed?");

my $results = timerdata::run_query("
	begin tran
	go

	$update_query

	commit tran
	go
");
die("theoretically impossible error occurred <<$results>>") unless
		$results =~ /^\(1 row affected\)\s*/;
print "\nmark was successful\n";
