#! /bin/ksh

. /usr/local/bin/kshlib

server=SYBASE_1
user=$USER
destdb=timertest

while getopts ":S:U:D:h" opt
do
	case $opt in
		S)  server=$OPTARG
			;;
		U)  user=$OPTARG
			;;
		D)  destdb=$OPTARG
			;;
		h)  echo "usage: $0 [-Sserver] [-Uusername] [-Ddest_db]" >&2
			echo "   defaults are -S$server -U$user -D$destdb" >&2
			exit
			;;
		:)  echo "$0: $OPTARG requires an argument ($0 -h for usage)" >&2
			exit
			;;
		\?) echo "illegal option; $0 -h for usage" >&2
			exit
	esac
done
shift $((OPTIND - 1))

run_query -S$server -U$user -D$destdb <<-END

	print 'creating todo_item'
	go

	$(overwrite_table todo_item "
		emp					char(3)			NOT NULL,
	")

	create unique index todo_item
	on todo_item ()
	go


END
