#! /usr/bin/perl

use strict;

use Storable;


my $users =
{
	101		=>		{
						fullname	=>		'Buddy Burden',
						nickname	=>		'buddy',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	109		=>		{
						fullname	=>		'Erik Wenberg',
						nickname	=>		'wenberg',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	112		=>		{
						fullname	=>		'Marcus Everidge',
						nickname	=>		'Marcus',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	119		=>		{
						fullname	=>		'Tim Weber',
						nickname	=>		'tweber',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	125		=>		{
						fullname	=>		'Gregg Thomason',
						nickname	=>		'Gregg',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	131		=>		{
						fullname	=>		'Jim Horner',
						nickname	=>		'beeker',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	132		=>		{
						fullname	=>		'Chris Weber',
						nickname	=>		'spyder',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	134		=>		{
						fullname	=>		'Christy Brunker',
						nickname	=>		'Christy',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	136		=>		{
						fullname	=>		'Mike Whitted',
						nickname	=>		'mike',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	139		=>		{
						fullname	=>		'Wayne Loy',
						nickname	=>		'wayner',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	140		=>		{
						fullname	=>		'Jay Vilhena',
						nickname	=>		'Jay',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	146		=>		{
						fullname	=>		'Randy Unger',
						nickname	=>		'randy',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	148		=>		{
						fullname	=>		'Marc Ward',
						nickname	=>		'marcw',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
};

store($users, "users.dat");
