#! /usr/bin/perl

use strict;

use Storable;


my $users =
{
	101		=>		{
						fullname	=>		'Buddy Burden',
						nickname	=>		'buddy',
						username	=>		'buddy',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	109		=>		{
						fullname	=>		'Erik Wenberg',
						nickname	=>		'wenberg',
						username	=>		'wenberg',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	112		=>		{
						fullname	=>		'Marcus Everidge',
						nickname	=>		'Marcus',
						username	=>		'marcus',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	119		=>		{
						fullname	=>		'Tim Weber',
						nickname	=>		'tweber',
						username	=>		'tweber',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	125		=>		{
						fullname	=>		'Gregg Thomason',
						nickname	=>		'Gregg',
						username	=>		'gregg',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	126		=>		{
						fullname	=>		'Gene Santomartino',
						nickname	=>		'Gene',
						username	=>		'gene_s',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	131		=>		{
						fullname	=>		'Jim Horner',
						nickname	=>		'beeker',
						username	=>		'jhorner',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	132		=>		{
						fullname	=>		'Chris Weber',
						nickname	=>		'spyder',
						username	=>		'elwebe',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	134		=>		{
						fullname	=>		'Christy Brunker',
						nickname	=>		'Christy',
						username	=>		'christy',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	136		=>		{
						fullname	=>		'Mike Whitted',
						nickname	=>		'mike',
						username	=>		'mike',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	139		=>		{
						fullname	=>		'Wayne Loy',
						nickname	=>		'wayner',
						username	=>		'wayne',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	140		=>		{
						fullname	=>		'Jay Vilhena',
						nickname	=>		'Jay',
						username	=>		'jay',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	146		=>		{
						fullname	=>		'Randy Unger',
						nickname	=>		'randy',
						username	=>		'runger',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	147		=>		{
						fullname	=>		'Sarah Hager',
						nickname	=>		'sarah',
						username	=>		'sarah',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	148		=>		{
						fullname	=>		'Marc Ward',
						nickname	=>		'marcw',
						username	=>		'marcw',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	150		=>		{
						fullname	=>		'Tom Ryan',
						nickname	=>		'Tom',
						username	=>		'tryan',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	151		=>		{
						fullname	=>		'Ramin Rad',
						nickname	=>		'raminr',
						username	=>		'raminr',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	152		=>		{
						fullname	=>		'Chris Strickland',
						nickname	=>		'strick',
						username	=>		'strick',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
	153		=>		{
						fullname	=>		'Dave Lee',
						nickname	=>		'David',
						username	=>		'dlee',
						location	=>		'Barefoot',
						groups		=>		'Barefoot',
					},
};

store($users, "users.dat");
