#! /usr/bin/perl

use strict;

use Barefoot::T3;
use Time::Local;
use CGI;

use constant HIST_FILE => 'Timer.his';
use constant BAK_FILE => 'Timer.bak';

T3::initialize($::ENV{HOME});

print STDERR "$0: no user name defined in ini file\n" and exit(1)
        unless defined($T3::username);

my $bak_filename = $ARGV[0] . "/" . BAK_FILE;
my $hist_filename = $ARGV[0] . "/" . HIST_FILE;

if (! -e $hist_filename) { die ("Error: No history file -- wrong directory?"); }
if (-e $bak_filename) { die ("Error: " . $bak_filename . " exists -- already converted?"); }

rename ($hist_filename, $bak_filename);

open(IN, $bak_filename) or die("Error: Can't open Timer.bak file for reading");
open(OUT, ">" . $hist_filename) or die("Error: Can't create new Timer.his file");

my $perlsecs = time;

while ( <IN> )
{
	chomp;

	# Handle special case for linebreaks
	s/&#13;&#10;/\<BR\>/g;
	s/
//g;

	s/<MESSAGE from=\"(.*?)\" location=\"\"/<$1>/;
	s/ time=\"(.*?)\" to=\"(.*?)\" status=\"NORMAL\"/<$2><$1>/;

	my $subject;
	my $message;

	if (s/ subject=\"(.*?)\"\>(.*?)<\/MESSAGE\>//)
	{
		$subject = $1;
		$message = $2;
	}

	print OUT $_;

	$subject =~ s/&gt;/GREATERTHANSIGN/g;
	$subject =~ s/&#62/GREATERTHANSIGN/g;
	$subject = CGI::unescapeHTML($subject);
	$subject =~ s/GREATERTHANSIGN/&#62/g;

	$message = CGI::unescapeHTML($message);

	print OUT "<$subject>$message
\n";
}
close(OUT);
close(IN);
