#! /usr/bin/perl

# For RCS:
# $Date$
#
# $Id$
# $Revision$

use strict;

use Barefoot::debug;							# comment out for production

use Getopt::Std;
use Barefoot::date;
use Barefoot::input qw(input);


my $opt = {};
getopts('lo:', $opt);
my $list_only = $opt->{l};
my $older_than = $opt->{o};

my %users;
open(LOG, "/var/log/httpd/access_log") or die("can't open server log");
while ( <LOG> )
{
	if ( /talker_server/ and /status="IM(ON|BUSY)"/ )
	{
		my ($from) = /from="(.*?)"/;
		$users{$from} = $_;
	}
}
close(LOG);

foreach my $user (keys %users)
{
	$_ = $users{$user};
	my ($date, $time) = /\[(.*?):(.*?) .*?\]/;
	my $secs = date::dateTimeSeconds($date, $time);
	$users{$user} = "$secs##$date $time";
}

foreach my $user (sort { $users{$a} <=> $users{$b} } keys %users)
{
	my $datetime = $users{$user};
	# print "    $datetime\n";
	$datetime =~ s/^(.*?)##//;
	next unless not $older_than or $1 < time() - $older_than * 60;
	print "$user";
	print ": $datetime" unless $list_only;
	print "\n";
}
