#! /usr/bin/perl

use strict;

# keep in mind this includes a call to t3_who, so debugging this
# can lead to weird path problems if you're not careful.
#use Barefoot::debug;		# comment out for production

use Barefoot::T3;
use Barefoot::input qw(input);


my $retval = 0;

if ($ARGV[0])
{
	foreach my $user (@ARGV)
	{
		$retval |= logoff($user);
	}
}
else
{
	if (-t STDIN)
	{
		my $user = input("user to log off?");
		$retval |= logoff($user);
	}
	else
	{
		exit(2);
	}
}
exit($retval);


sub logoff
{
	my ($user) = @_;

	if (!`t3_who | grep $user`)
	{
		print STDERR "$0: user $user doesn't appear to be logged in\n";
		return 1;
	}

	T3::send_message(T3::build_message(T3::LOGOFF_MESSAGE, "$user"));
	return 0;
}
