#! /usr/bin/perl

# For RCS:
# $Date$
#
# $Id$
# $Revision$

use strict;

# use Barefoot::debug;							# comment out for production

use Barefoot::T3;


chdir(T3::config_param('TalkerDir'));

print "The following people have waiting messages ...\n";
foreach my $box ( <*.box> )
{
	if ( -s $box )
	{
		my $line = `wc -l $box`;
		$line =~ s/\.box$//;
		print $line;
	}
}
