#! /usr/bin/perl

use strict;

#use Barefoot::debug;		# comment out for production

use Barefoot::T3;
use Getopt::Std;

my $opt={};

getopts('w:', $opt);
T3::set_workgroup($opt->{w}) if $opt->{w};

foreach (T3::send_message(T3::build_message(T3::INFO_MESSAGE)))
{
	my $attr = T3::parse_message($_);
	print "$attr->{from}\n" if $attr->{status} eq T3::USER_ON_MESSAGE
			or $attr->{status} eq T3::BUSY_MESSAGE;
}
